# Game Settings
max_players: 3

# Physics
rabbit_speed: 5
rabbit_jump_speed: 20
rabbit_revival_time: 5
rabbit_desintoxicate_time: 1

# Weapons

# BASIC GUN
basic_gun_fire_cooldown: 20
basic_gun_max_ammo: 999
basic_gun_damage: 1
basic_gun_range: 40
basic_gun_bullet_speed: 10

# MACHINE GUN
machinegun_fire_cooldown: 5
machinegun_max_ammo: 300
machinegun_damage: 1
machinegun_range: 40
machinegun_bullet_speed: 10
machinegun_ammo_amount: 10

# SNIPER 
sniper_fire_cooldown: 20
sniper_max_ammo: 10
sniper_damage: 3
sniper_range: 120
sniper_bullet_speed: 20
sniper_ammo_amount: 2

# Players
player_starting_life: 5
player_damage: 1

# Enemies
enemy_revive_cooldown: 400

# TURTLE: enemigo que se mueve de izquierda a derecha, solo hace daño si lo tocas.
enemy_turtle_speed: 2
enemy_turtle_damage: 1
enemy_turtle_life: 30
enemy_turtle_attack_range: 20
enemy_turtle_kill_points: 200

# LIZARD: enemigo que se mueve de izquierda a derecha, solo hace daño si lo tocas.
enemy_lizard_speed: 1
enemy_lizard_damage: 1
enemy_lizard_life: 50
enemy_lizard_attack_range: 10
enemy_lizard_kill_points: 100

# CRAB: enemigo que se mueve de izquierda a derecha, solo hace daño si lo pisas.
enemy_crab_speed: 3
enemy_crab_damage: 1
enemy_crab_life: 50
enemy_crab_attack_range: 0
enemy_crab_kill_points: 300

# Health Items
cant_health_carrot_life: 1

# Points
kill_rabbit_points: 1000
enemy_kill_points: 100
coin_points: 100
gem_points: 500
hot_dog_points: 200
hamburger_points: 300